import Head from "next/head";
import styles from "./LandingPage.module.scss";
import Link from "next/link";

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.LandingPage}>
        <h1>LandingPage</h1>
        <Link href="/login" className={styles.link}>
          Login
        </Link>
        <Link href="/home" className={styles.link}>
          Home
        </Link>
      </main>
    </>
  );
}
